### ISSUE TITLE
pp_concat_regrid: open_mf_wrf_dataset IOError

### ISSUE THREAD

**Issue by cm17nav** [wrfchem-leeds/WRFotron#28]
Hello,

I submitted pp_concat_regrid.bash, but received the following error from pp_concat_regrid.bash.e:

`Traceback (most recent call last):
  File "pp_concat_regrid.py", line 24, in <module>
    with salem.open_mf_wrf_dataset(filelist, chunks={'west_east':'auto', 'south_north':'auto'}) as ds:
  File "/nobackup/cm17nav/miniconda3/envs/python3_ncl_nco/lib/python3.8/site-packages/salem/sio.py", line 1169, in open_mf_wrf_dataset
    raise IOError('no files to open')
OSError: no files to open`

And lines 1166-1169 of `sio.py`, which follow the command to define open_mf_wrf_dataset, are

`if isinstance(paths, basestring):
        paths = sorted(glob(paths))
    if not paths:
        raise IOError('no files to open')`

My wrfout files are in the output directory too, so I'm not sure why they can't be found to be opened. Would a solution be for me to list the wrfout files within sio.py?

Many thanks,
Nadia

**Comment by lukeconibear** [comment]
Hi Nadia,

Thanks for posting this issue here.

Are you submitting `qsub pp_concat_regrid.bash` from within the `/output/base/` directory? Are the `year` and `month` set correctly within `pp_concat_regrid.py`? If so, then the `glob` function should pick up the local `wrfout` files from the current working directory following these [lines](https://github.com/wrfchem-leeds/WRFotron/blob/master/pp_concat_regrid.py#L19-L21).

The `IOError` from `sio.py` should just be `salem` letting you know it can't find the files.

If the above is all correct, then let me know the path to this run and I can take a look? (Ensure to allow me access rights using: `chmod a+rx -R /sim`).

**Comment by cm17nav** [comment]
Thanks, Luke. 

I did submit `pp_concat_regrid.bash` from within `/output/base/` and `year = '2015'` and `month = '6'`, which match my run. 

The path is `/nobackup/cm17nav/simulation_WRFChem4.2_NEW_China/output/base` and it should be accessible now.

**Comment by lukeconibear** [comment]
I think the issue is that the `month` string needs a preceding `0` for numbers 0-9, as it finds the files based on string matching. So currently it is searching for `wrfout_d01_2015-6-*` files rather than `wrfout_d01_2015-06-*` files.

Also, I noticed that one of your `wrfout` files looks faulty (too small). This is the file `wrfout_d01_2015-06-30_05:00:00` which is only 17 MB in size, when they should be 400-800 MB. You can find these faulty (smaller) filers via: `find ./wrfout* -size -100M`. It looks like this was the only faulty file.
So, first I would delete this faulty file from `output/base`.
Then looking in `run/base/staging`, `post.bash` may have run out of time when it got to this file.
So, delete both `tmp` files for this:
```bash
rm -f tmp_wrfout_d01_2015-06-30_05:00:00.nc wrfout_d01_2015-06-30_05:00:00.nc
```
Now, go to `run/base/2015-05-29_00:00:00-2015-07-01_00:00:00` and resubmit `post.bash` to post-process these final `wrfout` files (from `wrfout_d01_2015-06-30_05:00:00` to `wrfout_d01_2015-06-30_23:00:00`).

Let me know if this works.

**Comment by cm17nav** [comment]
Thanks, that was a daft mistake! I changed `month` to `06` and re-submitted `post.bash` and think I have the correct wrfout files now.

When I ran `pp_concat_regrid.bash` again, there was an issue with `reuse_weights=True` in `pp_concat_regrid.py` (`ValueError: to reuse weights, you need to provide either filename or weights`). 

I changed `reuse_weights` to `False` and tried running `.bash` again: I now have all of the regridded/concatenated `.nc` files in `/output/base`, but `pp_concat_regrid.bash.e` ended with `AttributeError: 'Regridder' has no attribute 'clean_weight_file'`. 

Should I be concerned, or should I just use the `.nc` files?

**Comment by lukeconibear** [comment]
Glad that worked.

Those `wrfout` files will be fine.

The weight reuse is just there to speed things up. I've updated [`pp_concat_regrid.py`](https://github.com/wrfchem-leeds/WRFotron/blob/master/pp_concat_regrid.py) so this should also work now.

I'll change this issue to resolved.
